# permissions for end users to edit commandhealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commandhealthcheck-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: commandhealthcheck-editor-role
rules:
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - commandhealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - commandhealthchecks/status
  verbs:
  - get
