---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - commandhealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - commandhealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - commandhealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - dnshealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - dnshealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - dnshealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - httphealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - httphealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - httphealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tcphealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tcphealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tcphealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tlshealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tlshealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tlshealthchecks/status
  verbs:
  - get
  - patch
  - update
