# permissions for end users to view tlshealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tlshealthcheck-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: tlshealthcheck-viewer-role
rules:
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tlshealthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - healthchecks.appclacks.com
  resources:
  - tlshealthchecks/status
  verbs:
  - get
