apiVersion: healthchecks.appclacks.com/v1alpha1
kind: CommandHealthcheck
metadata:
  name: commandhealthcheck-sample
  namespace: appclacks
  labels:
    example: label
spec:
  interval: 35s
  timeout: 10s
  description: "command health check example"
  enabled: false
  command: "ls"
  arguments:
    - "-l"
