apiVersion: healthchecks.appclacks.com/v1alpha1
kind: HTTPHealthcheck
metadata:
  name: httphealthcheck-sample
  namespace: appclacks
  labels:
    example: label
spec:
  description: "http health check example"
  interval: 30s
  enabled: true
  timeout: 5s
  validStatus: [200, 203]
  port: 443
  protocol: https
  redirect: true
  method: GET
  target: api.appclacks.com
  path: /healthz
  # headers:
  #   Foo: bar
  # query:
  #   param1: value
  # body: "body-content"
  # bodyRegexp:
  #   - "content"
  # key: "/path/to/cert.key"
  # cert: "/path/to/cert.pem"
  # cacert: "/path/to/cacert.pem"
  # insecure: true
  # enabled: false
  # serverName: api.appclacks.com
  # host: api.appclacks.com
