apiVersion: healthchecks.appclacks.com/v1alpha1
kind: TLSHealthcheck
metadata:
  name: tlshealthcheck-sample
  namespace: appclacks
  labels:
    example: label
spec:
  interval: 35s
  timeout: 10s
  description: "tls health check example"
  enabled: true
  target: google.com
  port: 443
  serverName: google.com
  # key: "/path/to/cert.key"
  # cert: "/path/to/cert.pem"
  # cacert: "/path/to/cacert.pem"
  # insecure: true
  # expirationDelay: 24h
