apiVersion: v1
kind: Namespace
metadata:
  name: appclacks
  labels:
    app.kubernetes.io/name: appclacks-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: appclacks-operator
  name: appclacks-operator
  namespace: appclacks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appclacks-operator
  namespace: appclacks
  labels:
    app.kubernetes.io/name: appclacks-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: appclacks-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appclacks-operator
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        envFrom:
          - secretRef:
              name: appclacks-credentials
        args:
        - --leader-elect
        image: appclacks/operator:v0.0.6
        name: appclacks-operator
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
      serviceAccountName: appclacks-operator
