# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/healthchecks.appclacks.com_dnshealthchecks.yaml
- bases/healthchecks.appclacks.com_tcphealthchecks.yaml
- bases/healthchecks.appclacks.com_tlshealthchecks.yaml
- bases/healthchecks.appclacks.com_httphealthchecks.yaml
- bases/healthchecks.appclacks.com_commandhealthchecks.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_dnshealthchecks.yaml
#- patches/webhook_in_tcphealthchecks.yaml
#- patches/webhook_in_tlshealthchecks.yaml
#- patches/webhook_in_httphealthchecks.yaml
#- patches/webhook_in_commandhealthchecks.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_dnshealthchecks.yaml
#- patches/cainjection_in_tcphealthchecks.yaml
#- patches/cainjection_in_tlshealthchecks.yaml
#- patches/cainjection_in_httphealthchecks.yaml
#- patches/cainjection_in_commandhealthchecks.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
